### ISSUE TITLE
Missing doc for ResponsiveNavigation

### ISSUE THREAD

**Issue by ryuken** [nordsoftware/react-foundation#14]
### What did you do?
Tried to use ResponsiveNavigation

### What did you expect to happen?
Rendering of titleBarTitle is unknown

### What actually happened?
Rendering of titleBarTitle is unknown

### What version of this module are you using?
latest

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```js
<ResponsiveNavigation titleBarTitle="Test">
                <TopBarLeft>
                    <Menu>
                        <MenuText>Test</MenuText>
                        <MenuItem isActive>
                            <a href="/">Home</a>
                        </MenuItem>
                    </Menu>
                </TopBarLeft>
                <TopBarRight>
                    <Menu alignment="right">
                        <MenuItem>Logoutt</MenuItem>
                    </Menu>
                </TopBarRight>
            </ResponsiveNavigation>
```

**Comment by crisu83** [comment]
Response navigation is probably going to get removed, because at least from our experienced it didn't really meet the requirements and we had to code a separate component in each project where we tried using it. I will have to take another look at this when I have time.

**Comment by crisu83** [comment]
I'm closing this since there has not been any activity lately.
