### ISSUE TITLE
npm WARN deprecated minimatch@0.3.0, minimatch@2.0.10, to-iso-string@0.0.2, jade@0.26.3, 

### ISSUE THREAD

**Issue by AlessandroMendozza** [nordsoftware/react-foundation#17]
### What did you do?
`npm install`

### What version of this module are you using?
`node v6.3.1`
`npm 3.10.3`

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
```

**Comment by crisu83** [comment]
These are just warnings from NPM, they are not direct dependencies so I wouldn't say that this is a valid issue for this project.

**Comment by AlessandroMendozza** [comment]
Alright guys I agree with you about npm WARN && (and) I believe in your project. So to grow I think you should improve your documentation e.g. to how to make it works with just a plug and play components like in this environment https://github.com/facebookincubator/create-react-app#getting-started then your documentation would to continue to how to deploy apps or a platform of apps into linux machines. 

Do you think it would be possible for you producing this? If yes in how much time?

Yours,
Alessandro
