### ISSUE TITLE
This npm module doesn't seem to work with webpack

### ISSUE THREAD

**Issue by myk5000** [nordsoftware/react-foundation#19]
### What did you do?
Installed react foundation

### What did you expect to happen?
It to work

### What actually happened? 
Objects would load without styles or functionally. CSS and js didn't look like it was loaded. Objects used were Link, Button, and Colors. No colors were added to any of the objects during render.

### What version of this module are you using? 
Latest as of today's date

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```js
code goes here
```

**Comment by Jalle19** [comment]
Could you perhaps elaborate on the `code goes here` part?

**Comment by crisu83** [comment]
We use this library in numerous projects everyday that runs Webpack, so without any further info it's hard to lend you a hand.

**Comment by myk5000** [comment]
You guys can close the issue. If you have time please add the web pack
loader sample for this package to the read me.  I believe that's what was
holding me up.

**Comment by myk5000** [comment]
Does react-foundation require foundation-sites? Looking at the start project there look to be more items required then listed in the readme directions, hard to tell from the package.json what is required.

**Comment by crisu83** [comment]
@myk5000 Well, it doesn't do anything visible if you don't have the style definitions so I guess you could say that it requires foundation-sites.

**Comment by myk5000** [comment]
So I'm new to both and want aware. Can you please update the wiki to show
all the needed dependencies
